name: HeckersPlugin
version: '${project.version}'
main: net.heckerdev.heckersplugin.HeckersPlugin
api-version: '1.17'
commands:
  kit:
    description: Gives you some items.
    usage: /kit <kit>
  book:
    description: Gives you a book.
    usage: /book
  spawn:
    description: Teleports you to spawn.
    usage: /spawn
  groups:
    description: Get the groups of yourself or another player
    usage: /groups (optional) <player>